### ISSUE TITLE
Anaconda3 Docker image does not have pip

### ISSUE THREAD

**Issue by jennirinker** [ContinuumIO/docker-images#122]
This is likely related to #120, but I'm not familiar enough with the linux build to explain.

My CI/CD pipelines that rely on the anaconda docker image have broken because pip is no longer recognized. I've tried it on two separate repos that both rely on the image and they both fail now.

### Example pipeline config block
```yaml
test_pyconturb:  # name the job what we like
  image: continuumio/anaconda3:latest
  stage:  # build, test, deploy defined by default [2]
    test
  script:  # install dev options, then code, then run tests and do coverage report
  - pip install pytest pytest-cov
  - pip install -e .
  - python -m pytest -m "not long" --cov-report term-missing:skip-covered --cov=pyconturb --cov-config .coveragerc
  tags:  # only runners with this tag can do the job [3]
  - python
```

### Example of failed pipeline output
```
Running with gitlab-runner 10.0.2 (a9a76a50)
  on synnefo-docker-iamge (761634a5)
Using Docker executor with image continuumio/anaconda3:latest ...
Using docker image sha256:8932848158968b014b012a13b2bb172aba7d0f769277cfbdd858942194f2d205 for predefined container...
Pulling docker image continuumio/anaconda3:latest ...
Using docker image continuumio/anaconda3:latest ID=sha256:9e186aada2eeee49531aa19229cf727fbab5a0d31aa15470cdf7e733647411d6 for build container...
Running on runner-761634a5-project-570-concurrent-0 via snf-713...
Fetching changes...
HEAD is now at 967a398 fixing tests
From https://gitlab.windenergy.dtu.dk/rink/pyconturb
   967a398..3f28676  restruct   -> origin/restruct
Checking out 3f286762 as restruct...
Skipping Git submodules setup
/bin/sh: eval: line 66: pip: not found
$ pip install pytest pytest-cov
ERROR: Job failed: exit code 127
```
