### ISSUE TITLE
continuumio:anaconda[3] does not work anymore from Gitlab CI

### ISSUE THREAD

**Issue by SmirnGreg** [ContinuumIO/docker-images#150]
Hi!
I am using Gitlab CI to test my code and publish documentation. I have a `.gitlab-ci.yml` file like this:
```yml
image: continuumio/anaconda
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V               # Print out python version for debugging
  - python setup.py install

test:
  script:
  - pytest --cov --hypothesis-show-statistics
```
It worked fine until recently. Now, for some reason, the python in docker is python2, not python3, that is not what I expect from anaconda3 container. Can it be that the old docker script installs the new version of conda incorrectly?
```bash
Running with gitlab-runner 12.1.0 (de7731dd)
  on docker-auto-scale 72989761
Using Docker executor with image continuumio/anaconda3:latest ...
Pulling docker image continuumio/anaconda3:latest ...
Using docker image sha256:cd83b04b81699f5853157435481d4d64dad2b2ff823aec52f451d315d29333cd for continuumio/anaconda3:latest ...
Running on runner-72989761-project-11202857-concurrent-0 via runner-72989761-srm-1567184261-56c2a032...
Fetching changes...
Initialized empty Git repository in /builds/ANDES-dev/pyndes/.git/
Created fresh repository.
From https://gitlab.com/ANDES-dev/pyndes
 * [new branch]      bugfix-conda-docker-fail -> origin/bugfix-conda-docker-fail
 * [new branch]      docker_fix -> origin/docker_fix
 * [new branch]      master     -> origin/master
Checking out 8598c1ea as docker_fix...

Skipping Git submodules setup
$ python -V
Python 2.7.16
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
ERROR: Job failed: exit code 1
```
