### ISSUE TITLE
Conda installed packages not found in container any more. 

### ISSUE THREAD

**Issue by sorenwacker** [ContinuumIO/docker-images#277]
For some reason, conda installed packages are not found anymore inside the container. 
First, I had issues that pip was not found during build. Now the build runs through, however I cannot start my service as Django is cannot be imported.

dockerfile:
```
FROM continuumio/miniconda3
ENV PYTHONUNBUFFERED=1
RUN mkdir /static
RUN apt update && apt install -y build-essential time libgraphviz-dev graphviz
RUN conda install -c conda-forge python==3.10 django==4 pip
COPY backend/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./backend /backend
WORKDIR /backend/
```

docker-compose.yml:
```
version: "3.3"
   
services:
  backend:
    container_name: backend
    restart: never
    #user: ${UID}
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile-backend
    env_file:
      - ./.env
    command: ./manage.py runserver --database docker
    volumes:
      - ./backend/:/backend/
      - ${STATIC}:/static/
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    container_name: db
    restart: always
    image: postgres:13.4
    volumes:
      - ${DB}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
```

I tried various things like actually creating an environment this;

    SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]

(I also changed the command in the docker-compose file accordingly, but nothing wored so far.)

I am a bit puzzled, because the same setup ran smoothly since almost a year in another project, and I did not have to add such things. Did something change with the image?
